# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install
      - run: 
          name: Build project
          command: |
            export NODE_ENV=development
            export REACT_APP_CLIENT=mock
            export REACT_APP_AUTHENTICATION=mock
            yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Deploy Preview
          command: if [ -n "$CIRCLE_PULL_REQUEST" ]; then .circleci/upload_preview.sh; fi

      # Run tests
      - run: yarn test

      # Run coverage
      - run: yarn codecov

